export enum MessageType {
	setDeployments = "SET_DEPLOYMENTS",
	setProjectName = "SET_PROJECT_NAME",
	setResourcesDirState = "SET_RESOURCES_DIR_STATE",
	setTheme = "SET_THEME",
	runProject = "RUN_PROJECT",
	onClickSetResourcesDirectory = "ON_CLICK_SET_RESOURCES_DIRECTORY",
	buildProject = "BUILD_PROJECT",
	setSessionsSection = "SET_SESSIONS_SECTION",
	selectDeployment = "SELECT_DEPLOYMENT",
	displaySessionLogs = "DISPLAY_SESSION_LOGS",
	deactivateDeployment = "DEACTIVATE_DEPLOYMENT",
	activateDeployment = "ACTIVATE_DEPLOYMENT",
	setSessionExecutionInputs = "COPY_TO_CLIPBOARD",
	runExecution = "RUN_EXECUTION",
	setEntrypoints = "SET_ENTRYPOINTS",
	setExecutionInputsDefined = "SET_EXECUTION_INPUTS",
	saveExecutionProps = "SAVE_EXECUTION_PROPS",
}
