export const namespaces = {
	applyManifest: "Manifest Application",
	connection: "Connection",
	serverRequests: "Server Requests",
	deploymentsService: "Deployments Service",
	environmentsService: "Environments Service",
	manifestService: "Manifest Service",
	projectService: "Project Service",
	projectController: "Project Controller",
	sessionsService: "Sessions Service",
	sessionsHistory: "Sessions History",
	appStateHandler: "Application State",
	sessionLogs: "Session Logs",
	startlarkLSPServer: "Starlark LSP",
};
