export const namespaces = {
	applyManifest: "Manifest Application",
	connection: "Connection",
	serverRequests: "Server Requests",
	deploymentsService: "Deployments Service",
	environmentsService: "Environments Service",
	manifestService: "Manifest Service",
	projectService: "Project Service",
	resourcesService: "Resources Service",
	projectController: "Project Controller",
	projectSidebarController: "Project Sidebar Controller",
	sessionsService: "Sessions Service",
	sessionsHistory: "Sessions History",
	appStateHandler: "Application State",
	sessionLogs: "Session Logs",
	buildRuntimeEntrypoints: "Convert runtime to entrypoints",
	connectionsController: "Connections Controller",
};
