export const vsCommands = {
	openWebview: "autokitteh.openWebview",
	connect: "autokitteh.connect",
	testConnection: "autokitteh.testConnection",
	disconnect: "autokitteh.disconnect",
	applyManifest: "autokitteh.applyManifest",
	buildFolder: "autokitteh.buildFolder",
	openBaseURLInputDialog: "autokitteh.openBaseURLInputDialog",
	openConfigSetupWalkthrough: "autokitteh.openConfigSetupWalkthrough",
	buildProject: "autokitteh.buildProject",
	runProject: "autokitteh.runProject",
	openWalkthrough: "workbench.action.openWalkthrough",
	baseURLUpdated: "autokitteh.baseURLUpdated",
	showErrorMessage: "autokitteh.showErrorMessage",
	showInfoMessage: "autokitteh.showInfoMessage",
	downloadExecutableDialog: "autokitteh.downloadExecutableDialog",
};
