export const vsCommands = {
	openWebview: "autokitteh.openWebview",
	connect: "autokitteh.connect",
	disconnect: "autokitteh.disconnect",
	applyManifest: "autokitteh.applyManifest",
	buildFolder: "autokitteh.buildFolder",
	openUsernameInputDialog: "autokitteh.openUsernameInputDialog",
	usernameUpdated: "autokitteh.usernameUpdated",
	openBaseURLInputDialog: "autokitteh.openBaseURLInputDialog",
	walkthrough: "autokitteh.walkthrough",
	openWalkthrough: "workbench.action.openWalkthrough",
	baseURLUpdated: "autokitteh.baseURLUpdated",
	showErrorMessage: "autokitteh.showErrorMessage",
	showInfoMessage: "autokitteh.showInfoMessage",
};
