export const vsCommands = {
	openWebview: "autokitteh.openWebview",
	enable: "autokitteh.enable",
	disable: "autokitteh.disable",
	applyManifest: "autokitteh.applyManifest",
	buildFolder: "autokitteh.buildFolder",
	openBaseURLInputDialog: "autokitteh.openBaseURLInputDialog",
	openConfigSetupWalkthrough: "autokitteh.openConfigSetupWalkthrough",
	buildProject: "autokitteh.buildProject",
	runProject: "autokitteh.runProject",
	openWalkthrough: "workbench.action.openWalkthrough",
	baseURLUpdated: "autokitteh.baseURLUpdated",
	showErrorMessage: "autokitteh.showErrorMessage",
	showInfoMessage: "autokitteh.showInfoMessage",
	downloadExecutableDialog: "autokitteh.downloadExecutableDialog",
	addConnections: "autokitteh.addConnections",
	setContext: "autokitteh.setContext",
	getContext: "autokitteh.getContext",
	setAuthToken: "autokitteh.setAuthToken",
	setBaseURL: "autokitteh.setBaseURL",
};
