name: Node.js CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}
          submodules: true
      - uses: actions/setup-node@v3
        with:
          node-version: "21.2.0"
          cache: "npm"
      - name: Get submodule from remote
        run: git submodule update --remote
      - name: Install vscode-dependencies
        run: npm ci
      - name: Install vscode-tests
        run: npm test -- --watch=false
      - name: Run vscode TS validation
        run: npm run compile
      - name: Build vscode extension
        run: npm run esbuild
      - name: Test and build vscode-webview-ui
        run: |
          cd webview-ui
          npm ci
          npm run test
          npm run build
      - name: Release and tag a new version
        run: npx semantic-release
