name: autokittehVSCode CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}
          submodules: true
      - uses: actions/setup-node@v3
        with:
          node-version: "21.2.0"
          cache: "npm"
      - name: Pull submodule from remote
        run: git submodule update --remote
      - name: Install dependencies for both vscode and react app
        run: npm ci
      - name: Run vscode and react app tests
        run: npm run test:all
      - name: Run vscode TS validation and react app
        run: npm run compile:all
      - name: Build vscode extension and react app
        run: npm run build:all
      - name: Release and tag a new version
        run: npx semantic-release
