name: autokittehVSCode CI
on:
  push:
env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}
          submodules: true
      - uses: actions/setup-node@v3
        with:
          node-version: "21.2.0"
          cache: "npm"
      - name: Pull submodule from remote
        run: git submodule update --remote
      - name: Install dependencies for both vscode and react app
        run: npm ci
      - name: Run vscode and react app tests
        run: npm run test:all
      - name: Run vscode TS validation react app
        run: npm run compile:vscode-react
      - name: Run vscode TS build react app
        run: npm run build:vscode-react
      - name: Run vscode TS validation extension
        run: npm run compile
      - name: Build vscode extension
        run: npm run build
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: built-files
          path: |
            ./dist
            ./vscode-react/build

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev'
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}
          submodules: true
      - uses: actions/download-artifact@v3
        with:
          name: built-files
      - uses: actions/setup-node@v3
        with:
          node-version: "21.2.0"
          cache: "npm"
      - name: Install dependencies for both vscode and react app
        run: npm ci
      - name: Release and tag a new version
        env:
          SLACK_WEBHOOK_URL: ${{ github.ref == 'refs/heads/main' && secrets.SLACK_WEBHOOK_URL || github.ref == 'refs/heads/dev' && secrets.SLACK_WEBHOOK_URL_BETA }}
        run: npx semantic-release
