name: autokittehVSCode CI
on:
  push:
env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}
          submodules: true
      - uses: actions/setup-node@v3
        with:
          node-version: "21.2.0"
          cache: "npm"
      - name: Pull submodule from remote
        run: git submodule update --remote
      - name: Install dependencies for both vscode and react app
        run: npm ci
      - name: Run vscode and react app tests
        run: npm run test:all
      - name: Run vscode TS validation and react app
        run: npm run compile:all
      - name: Build vscode extension and react app
        run: npm run build:all
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: built-files
          path: ./dist

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev'
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}
          submodules: true
      - uses: actions/download-artifact@v3
        with:
          name: built-files
          path: ./dist
      - uses: actions/setup-node@v3
        with:
          node-version: "21.2.0"
          cache: "npm"
      - name: Install dependencies for both vscode and react app
        run: npm ci
      - name: Set Slack Webhook URL
        run: |
          if [[ "${{github.base_ref}}" == "main" || "${{github.ref}}" == "refs/heads/main" ]]; then
            export SLACK_WEBHOOK_URL=$SLACK_WEBHOOK_URL
          fi

          if [[ "${{github.base_ref}}" == "dev" || "${{github.ref}}" == "refs/heads/dev" ]]; then
            export SLACK_WEBHOOK_URL=$SLACK_WEBHOOK_URL_BETA
          fi
      - name: Release and tag a new version
        run: npx semantic-release
