name: autokittehVSCode CI - Publish to VSCode Marketplace

on:
  workflow_dispatch:
    inputs:
      release-type:
        type: choice
        description: "Release type"
        options:
          - "pre-release"
          - "release"
        required: true
      tag:
        type: string
        description: "Git tag to publish"
        required: true

jobs:
  publish-pre-release-to-marketplace:
    name: Publish Pre-Release to VSCode Marketplace
    if: github.event.inputs.release-type == 'pre-release'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.tag }}
          token: ${{ secrets.PAT_TOKEN }}
          submodules: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "21.2.0"
          cache: "npm"

      - name: Build from scratch pre-release extension version
        run: |
          git submodule update --remote
          npm ci
          npm run compile:all
          npm run build:all

      - name: Publish to VSCode Marketplace as pre-release
        run: npx vsce publish -p ${{ secrets.VSCE_TOKEN }} --pre-release

  publish-to-marketplace:
    name: Publish to VSCode Marketplace
    if: github.event.inputs.release-type == 'release'
    runs-on: ubuntu-latest
    steps:
      - name: Download and prepare release vsix from github repository
        run: |
          curl -sL -o extension.vsix "$(curl -sH "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/autokitteh/vscode-extension/releases/tags/${{ github.event.inputs.tag }} | jq -r '.assets[] | select(.name | endswith(".vsix")) | .browser_download_url')"

      - name: Publish to VSCode Marketplace
        run: npx vsce publish -p ${{ secrets.VSCE_TOKEN }} --packagePath extension.vsix
