name: autokittehVSCode CI - Publish to VSCode Marketplace

on:
  workflow_dispatch:
    inputs:
      release-type:
        type: choice
        description: "Release type"
        options:
          - "pre-release"
          - "release"
        required: true
      tag:
        type: string
        description: "Git tag to deploy"
        required: true

permissions:
  contents: write
  repository-projects: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.tag }}
          token: ${{ secrets.PAT_TOKEN }}
          submodules: true
      - uses: actions/setup-node@v3
        with:
          node-version: "21.2.0"
          cache: "npm"
      - name: Pull submodule from remote
        run: git submodule update --remote
      - name: Install dependencies for both vscode and react app
        run: npm ci
      - name: Compile vscode and react app
        run: npm run compile:all
      - name: Build vscode and react app
        run: npm run build:all
      - name: Publish to VSCode Marketplace
        uses: lannonbr/vsce-action@3.0.0
        with:
          args: ${{ github.event.inputs.release-type == 'pre-release' && 'publish -p ${{ secrets.VSCE_TOKEN }} --pre-release' || 'publish -p ${{ secrets.VSCE_TOKEN }}' }}
        env:
          VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
