name: Publish to VSCode Marketplace

on:
  workflow_dispatch:
    inputs:
      release-type:
        type: choice
        description: "Release type"
        options:
          - "pre-release"
          - "release"
        required: true
      tag:
        type: string
        description: "Git tag to publish"
        required: true

jobs:
  publish-to-marketplace:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}
          ref: ${{ github.event.inputs.tag }}
          submodules: true

      - uses: actions/setup-node@v3
        with:
          node-version: "21.2.0"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Compile and build extension to ensure everything is working
        run: npm run compile:all && npm run build:all

      - name: Release and Tag a New Version
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          if [ "${{ github.event.inputs.release-type }}" == "pre-release" ]; then
            npx semantic-release --branches beta
          else
            npx semantic-release
          fi

      - name: Install Dependencies Again (If needed)
        run: npm ci

      - name: Re-Compile and Build with New Version
        run: npm run compile:all && npm run build:all

      - name: Package & Publish VSCode Extension
        run: |
          VSCE_OPTIONS="--packagePath autokitteh.vsix"

          if [ "${{ github.event.inputs.release-type }}" == "pre-release" ]; then
            npx vsce package --pre-release -o autokitteh.vsix
            VSCE_OPTIONS="$VSCE_OPTIONS --pre-release"
          else
            npx vsce package -o autokitteh.vsix
          fi

          echo "Running vsce publish with options: $VSCE_OPTIONS"
          npx vsce publish -p ${{ secrets.VSCE_TOKEN }} $VSCE_OPTIONS
